FILENAME = proj5
ZIPNAME = xbobol00-fit.zip

all:
	pdflatex $(FILENAME).tex
	pdflatex $(FILENAME).tex

makezip:
	zip $(ZIPNAME) $(FILENAME).tex Makefile img/binary_tree.eps img/binary_tree_delete.png img/binary_tree_insert.png
