#ifndef IFJ20C_RETURN_CODES_H
#define IFJ20C_RETURN_CODES_H

#define OK 0
#define LEXICAL_ERROR 1
#define SYNTAX_ERROR 2
#define SEMANTIC_ERROR_UNDEFINED_VARIABLE 3
#define SEMANTIC_ERROR_DATA_TYPE 4
#define SEMANTIC_ERROR_TYPE_COMPATIBILITY 5
#define SEMANTIC_ERROR_FUNCTION 6
#define SEMANTIC_ERROR_OTHERS 7
#define SEMANTIC_ERROR_ZERO_DIV 9
#define INTERNAL_ERROR 99

#endif //IFJ20C_RETURN_CODES_H